{% set name = "configurator" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/configurator-{{ version }}.tar.gz
  sha256: 83a5f52434de26892c8b2d5e3618a187ae09f2aae1f2c945317e447d485956ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pyyaml
    - toml

test:
  imports:
    - configurator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Simplistix/configurator
  summary: A library for building a configuration store from one or more layered configuration sources
  license: MIT
  license_file: docs/license.rst

extra:
  recipe-maintainers:
    - chrisburr
