{% set name = "configurator" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/configurator-{{ version }}.tar.gz
  sha256: e88da11063f10c9529df08c8bd953d875bb7bdd781a14505f0cc32eabf06062d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - configurator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Simplistix/configurator
  summary: A library for building a configuration store from one or more layered configuration sources
  doc_url: https://configurator.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cjw296
    - chrisburr
    - cjw296
